### ISSUE TITLE
Feature request: add versioning to kikit-multipanel

### ISSUE THREAD

**Issue by nopeppermint** [snhobbs/kikit-multipanel#3]
* kikit-multipanel version: XX => does not yet exist
* Python version: 3.10.12
* Operating System: Linux Mint 21.2

### Description

Would be nice if kikit-multipanel has a version number and if it would be accessible via ``kikit_multipanel --version`` on the command line.

and thanks btw. for this tool, I have not yet found out how to get it working but looks promising ;-)

**Comment by snhobbs** [comment]
Added  with V0.1.1, good point!
