### ISSUE TITLE
is there any tips about means of panel.xlsx?

### ISSUE THREAD

**Issue by iysheng** [snhobbs/kikit-multipanel#8]
* kikit-multipanel version:0.1.2
* Python version:3.11
* Operating System:fedora38

### Description
wht'a the mean of xmm, ymm, x, y and space? 

### What I Did

```
I want to use this tool  to panel three boards of main, these boards shape as below:
77mm*53mm
60mm*32mm
32mm*32mm
```
![](https://s3.bmp.ovh/imgs/2024/01/03/e25e192389f88fe2.png)

**Comment by snhobbs** [comment]
xmm and ymm are the placement coordinate in mm. KiCAD uses nanometers as its base unit. The spacing is in mm, that probably is unnecessarily confusing... 

You'll need to include additional boards to fill in the open gaps in your arrangement as that isn't done automatically.

**Comment by iysheng** [comment]
> xmm and ymm are the placement coordinate in mm. KiCAD uses nanometers as its base unit. The spacing is in mm, that probably is unnecessarily confusing...
> 
> You'll need to include additional boards to fill in the open gaps in your arrangement as that isn't done automatically.

Thanks for you patient reply.
